modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/Mrbysco/GenerikMobs/issues"
license="MIT"

[[mods]]
modId="generikmobs"
version="${file.jarVersion}"
displayName="Generik Mobs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/generik-mobs"
authors="Mrbysco, GenerikB"
description='''
Booger me Eaters... Adds various mobs that are perfect for stream integration
'''
[[dependencies.generikmobs]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"