package com.mrbysco.generikmobs.client.animation;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class HummingbirdAnimations {

	public static final AnimationDefinition FLY = AnimationDefinition.Builder.withLength(2f).looping()
			.addAnimation("main",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25f, KeyframeAnimations.posVec(-4f, 3f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6766666f, KeyframeAnimations.posVec(-4f, 3f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7916766f, KeyframeAnimations.posVec(2f, 5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.2916767f, KeyframeAnimations.posVec(2f, 5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4167667f, KeyframeAnimations.posVec(4f, 1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.625f, KeyframeAnimations.posVec(4f, 1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("cigar",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(0f, 0f, 2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.375f, KeyframeAnimations.degreeVec(0f, 0f, -5.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(0f, 6f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("smoke",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 50f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, -20f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.75f, KeyframeAnimations.degreeVec(17.5f, 0f, -20f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(0f, 0f, 25f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.125f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.375f, KeyframeAnimations.degreeVec(0f, 0f, -12.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.625f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.75f, KeyframeAnimations.degreeVec(0f, 0f, 32.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.875f, KeyframeAnimations.degreeVec(0f, 0f, -17.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("smoke",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(1.2916767f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.3433333f, KeyframeAnimations.scaleVec(1f, 1.2f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4583433f, KeyframeAnimations.scaleVec(1f, 0.7f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5834333f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_eyebrow",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25f, KeyframeAnimations.posVec(0f, -0.1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, -0.1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7916766f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.3433333f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4167667f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7083433f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7916767f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_eyebrow",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_eyebrow",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25f, KeyframeAnimations.posVec(0f, -0.1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, -0.1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7916766f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.3433333f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4167667f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7083433f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7916767f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_eyebrow",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(0f, 0f, 2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_wing",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.625f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.125f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.2083433f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.375f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5416767f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.625f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.75f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.875f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.9167667f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.9583433f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_wing",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.625f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.125f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.2083433f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.375f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5416767f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.625f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.75f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.875f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.9167667f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.9583433f, KeyframeAnimations.degreeVec(0f, 0f, -47.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 47.5f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(0f, 0f, -1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(2.5f, 0f, 4f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(-2f, 2f, -1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(-2f, 2f, -1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.625f, KeyframeAnimations.degreeVec(-2f, 2f, -1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(-2f, 2f, -1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.75f, KeyframeAnimations.degreeVec(0f, 0f, 2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("tail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(1f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.125f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.625f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.125f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.2083433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.375f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.625f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.9583433f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2f, KeyframeAnimations.degreeVec(1f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(3.75f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.125f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.625f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.125f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.2083433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.375f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.625f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.9583433f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2f, KeyframeAnimations.degreeVec(3.75f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(3.75f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.125f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.625f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.125f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.2083433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.375f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.625f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.9583433f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2f, KeyframeAnimations.degreeVec(3.75f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body_2",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.08343333f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0834333f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.1676667f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.25f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.3433333f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4167667f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5834333f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.6766667f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.75f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.9167667f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body_2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.75f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.25f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.75f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.9167667f, KeyframeAnimations.degreeVec(2f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head_animation",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, -2.5f, 2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, -2.5f, 2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(2f, 2f, -2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(2f, 2f, -2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(-3f, 5.5f, -2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(-3f, 5.5f, -2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("main_2",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.08343333f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0834333f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.1676667f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.25f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.3433333f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4167667f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5834333f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.6766667f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.75f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.9167667f, KeyframeAnimations.posVec(0f, 0.05f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR))).build();
}
